import { Button , VerticalBox, HorizontalBox} from "std-widgets.slint";

export component Main inherits Window {
    title: "相机";
    icon: @image-url("../favicon.png");
    width: 640px;
    height: 640px;

    pure callback render-image(int) -> image;
    in-out property <int> frame;

    VerticalLayout { 
        HorizontalLayout {
            padding-right: 10px;
            padding-top: 10px;
            Button {
                font-size: 16px;
                width: 80px;
                height: 40px;
                text: "按钮";
                clicked => {  }
            }
        }
        HorizontalLayout {
            alignment: center;
            padding-top: 10px;
            Rectangle {
                border-color: gray;
                border-width: 1px;
                width: 640px;
                height: 480px;
                Image {
                    width: 100%;
                    height: 100%;
                    source: render-image(frame);
                }
            }
        }
    }
}